# Generated by Django 4.2.1 on 2023-06-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0002_botusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='категория трат')),
            ],
            options={
                'verbose_name': 'категория трат',
                'verbose_name_plural': 'категории трат',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spending.botusers', verbose_name='юзер бота')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spending.spendingcategory', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'трата',
                'verbose_name_plural': 'траты',
                'ordering': ['-id'],
            },
        ),
    ]
