# Generated by Django 4.2.1 on 2023-06-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0004_alter_botusers_language_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botusers',
            name='telephone',
        ),
    ]
